### ISSUE TITLE
SDKs - Provide Sandbox Account Utility Functions

### ISSUE THREAD

**Issue by barnjamin** [algorand-devrel/community#20]
Provide methods in the SDKs to pull accounts from the `unencrypted-default-wallet` that is created with dev/release/beta private networks.

This allows demos to be executed directly rather than doing some copy/paste of mnemonics into source which is terrible practice

**Comment by jeremyv3** [comment]
Methods in the main SDK's feel like the wrong place for this dev only type use.  Could you expand more on how it might work?  

If there was a way to make them useful via all the SDK's for production use as well I could see it but otherwise it seems more like it could end up as extra app weight in some SDK types like java for example.  Maybe a separate dev helper SDK package?

**Comment by barnjamin** [comment]
@jeremyv3 I am leaning the same direction as well. 

I end up copy/pasting something like this in a lot of my examples. Maybe a separate repo like sandbox-utils would make sense

```py
from algosdk.kmd import KMDClient

KMD_ADDRESS = "http://localhost:4003"
KMD_TOKEN = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

KMD_WALLET_NAME = "unencrypted-default-wallet"
KMD_WALLET_PASSWORD = ""

def get_accounts():
    kmd = KMDClient(KMD_TOKEN, KMD_ADDRESS)
    wallets = kmd.list_wallets()

    walletID = None
    for wallet in wallets:
        if wallet["name"] == KMD_WALLET_NAME:
            walletID = wallet["id"]
            break

    if walletID is None:
        raise Exception("Wallet not found: {}".format(KMD_WALLET_NAME))

    walletHandle = kmd.init_wallet_handle(walletID, KMD_WALLET_PASSWORD)

    try:
        addresses = kmd.list_keys(walletHandle)
        privateKeys = [
            kmd.export_key(walletHandle, KMD_WALLET_PASSWORD, addr)
            for addr in addresses
        ]
        kmdAccounts = [(addresses[i], privateKeys[i]) for i in range(len(privateKeys))]
    finally:
        kmd.release_wallet_handle(walletHandle)

    return kmdAccounts
```

**Comment by jeremyv3** [comment]
Yeh I can definitely see the usefulness.  I think you're right a separate utils package makes more sense.  Really I could see it being a part of a more generalized dev helper utils package.  Then if people find it useful in their language they can contribute their translation back fairly easy.
