### ISSUE TITLE
Learning Project Assignments List

### ISSUE THREAD

**Issue by jeremyv3** [algorand-devrel/community#21]
For learning purposes it would be nice to have some learning projects that were not tutorials per se but more like homework assignments.  The requirements of the task could be defined for what's needed but the answers could be submitted as branchs of the main projects list.  This could allow the learner to create their own implementation but also review how others have solved the problem.  There were a couple of these learning tasks put forward in the forum I believe but nothing lately or as well organized in a github repo.

**Comment by barnjamin** [comment]
This is addressed with challenges
