### ISSUE TITLE
SDKs - Provide a `min_balance` like function

### ISSUE THREAD

**Issue by barnjamin** [algorand-devrel/community#9]
Often application creators will want to check the min balance on an account prior to asking them to sign some transaction to ensure the transaction wont immediately fail.

At the moment the min balance may be computed given the parameters in the equation but each application creator needs to implement this logic on their own. This is brittle in the case the parameters change in the future.

We should provide in the SDKs or the APIs a way to get the min balance for a given account.

**Comment by pbennett** [comment]
This could be used by the wallet as well for example, showing the user exactly what their minimum balance is, and why.

**Comment by barnjamin** [comment]
This is now available in the Algod API
